// <auto-generated />
using Barlang.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Barlang.Migrations
{
    [DbContext(typeof(BarlangDbContext))]
    [Migration("20250930062300_sqlite.local_migration_926")]
    partial class sqlitelocal_migration_926
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Barlang.Models.Barlang", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("hossz")
                        .HasColumnType("INTEGER");

                    b.Property<int>("kiterjedes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("magassag")
                        .HasColumnType("INTEGER");

                    b.Property<int>("melyseg")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("telepules")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Barlangok");
                });
#pragma warning restore 612, 618
        }
    }
}
